<?php/** * @package   copix * @subpackage auth * @version   $Id: CopixPHPBBUser.class.php,v 1.1 2005/03/14 14:03:43 sdaclin Exp $ * @author   Sylvain DACLIN, Croes Gérald *           see copix.aston.fr for other contributors. * @copyright 2001-2005 CopixTeam * @link      http://copix.aston.fr * @link      http://copix.org * @licence  http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public Licence, see LICENCE file */
/** * @ignore */require_once (COPIX_AUTH_PATH.'CopixUser.class.php');
/**
 * Handle phpBB authentification for copix *
 * Use internal phpBB account info to log into copix * @package   copix * @subpackage auth */class CopixPHPBBUser extends CopixUser {   /**    * the base queryString we'll use to connect the user to    * There are special variables taht will be replaced:    * [--FIELDS--] replaced by the fields list    * [--USERTABLE--] replaced by the table where the users are    * [--LOGINFIELD--] replaced by the login field    * [--LOGIN--] replaced by the login we try to use to log in    * [--PASSWORDFIELD--] Where the password is    * [--PASSWORD--] the given password we're trying to log in with    * @var string    */   var $loginRequest  = 'SELECT [--FIELDS--] from [--USERTABLE--]                         WHERE  [--LOGINFIELD--] = [--LOGIN--]                         AND [--PASSWORDFIELD--] = [--PASSWORD--]';
   /**    * The fields we want to retrieve when logged in    * @var array    */   var $fieldPropList = array ('username'=>'login', 'user_email'=>'email');
   /**    * The table we wants to use for the login process    * @var string    */   var $userTable     = 'phpbb_users';
   /**    * The login field    * @var string    */   var $loginField    = 'username';
   /**    * the password field    * @var string    */   var $passwordField = 'user_password';
   /**    * Constructor    */   function CopixDBUser (){      parent::CopixUser ();   }
   /**    * Says if the login is successfull    * If successfull loads the users properties
    * @private    * @param string  $name   login    * @param string  $password   mot de passe    * @return boolean indique si authentification ok ou pas    */   function _doLogin ($name, $password=null){      //Création de la requête utilisateur, par remplacement des différents      //Champs de paramètres si fournits.
      //$this->userTable = 'phpbb_users';      $request = $this->_getParsedRequest ($this->loginRequest);      //remplacement de login / password.      $request = $this->_getParsedRequestLoginPassword ($request, $name, $password);
      $dbw = CopixDbFactory::getDbWidget();      if( $r = $dbw->fetchFirst ($request)){
         $this->_loadParams ($r);         return true;      }else{         return false;      }   }
   /**    * Charge les paramètres sur l'objet utilisateur, a partir de la requête envoyée.
    * @private    */   function _loadParams ($objInfos){      //parcour des champs, mise à jour de l'utilisateur.      foreach ($this->fieldPropList as $field=>$userField) {         $this->$userField = $objInfos->$field;      }   }
   /**    * Récupération de la liste des utilisateurs.    * @return    array   liste des utilisateurs    */   function getList (){      $userobjectname = get_class ($this);      $toReturn = array ();      $ct = CopixDBFactory::getDBWidget ();
      $rs = $ct->doSelect ($this->userTable, array_keys($this->fieldPropList), array ());      while ($r = $rs->fetch ()){         $pu = new $userobjectname ();         foreach ($this->fieldPropList as $field=>$userField) {            $pu->$userField = $r->$field;         }         $toReturn[] = $pu;      }      return $toReturn;   }
   /**    * gets the user
    * @param string login
    * @return record user    */   function get ($login){      $userobjectname = get_class ($this);      $ct = CopixDBFactory::getConnection();      $query = 'select '.implode (',', array_keys($this->fieldPropList)).' from '.$this->userTable.' where '.$this->loginField.' = '.$ct->quote ($login);      $rs = $ct->doQuery ($query);      if ($r = $rs->fetchUsing ($userobjectname)){         return $r;      }      return null;   }
   /**    * find users by login    * @param string $pattern the pattern we're looking for (does not contains special chars)
    * @return array list of users    */   function findByLogin ($pattern){      $userobjectname = get_class ($this);      $ct = CopixDBFactory::getConnection();      $query = 'SELECT '.implode (',', array_keys($this->fieldPropList)).' FROM '.$this->userTable.' WHERE '.$this->loginField.' LIKE '.$ct->quote ('%'.$pattern.'%');      $rs = $ct->doQuery ($query);      while ($r = $rs->fetch ()){         $pu = new $userobjectname ();         foreach ($this->fieldPropList as $field=>$userField) {            $pu->$userField = $r->$field;         }         $toReturn[] = $pu;      }      return $toReturn;   }
   /**    * Gets the right parsed query (replace the special patterns with the matching fields)    * @param string  $request    requête SQL avec les tags à remplacer    * @return string  requête finale    */   function _getParsedRequest ($request){      //la liste des champs.      $fieldString = implode (', ', array_keys ($this->fieldPropList));      $request = str_replace('[--FIELDS--]', $fieldString, $request);
      //remplacement de la table des users.      $request  = str_replace ('[--USERTABLE--]', $this->userTable, $request);
      //Remplacement du champ de login.      $request = str_replace ('[--LOGINFIELD--]', $this->loginField, $request);
      //remplacement du champ password.      return str_replace ('[--PASSWORDFIELD--]', $this->passwordField, $request);   }
   /**    * récupération de la requete avec les logins / password.    * @param string  $request    requête SQL avec les tags login/password à remplacer    * @return    string  requête finale    */   function _getParsedRequestLoginPassword ($request, $login, $password){      $ct = & CopixDbFactory::getConnection ();      $request = str_replace ('[--LOGIN--]', $ct->quote ($login), $request);      return str_replace ('[--PASSWORD--]', $ct->quote ($this->cryptPassword ($password)), $request);   }
   /**    * Updates the users password    * @param string $login the login    * @param string $newPassword the new password (clear)    * @return boolean    */   function updatePassword ($login, $newPassword){      $ct = CopixDBFactory::getConnection ();      $query = 'UPDATE '.$this->userTable.' SET '.$this->passwordfield.'='.$ct->quote ($this->cryptPassword($newPassword)).' WHERE '.$this->loginField.'='.$ct->quote ($login);      return $ct->doQuery ($query);   }
   /**    * Updates the users informations    * @param string $login the login    * @param array $informations the informations to update    * @return boolean    */   function updateInformations ($login, $informations){      $ct = & CopixDBFactory::getConnection ();      //Creating hash table to get field names from properties      foreach ($this->fieldPropList as $key=>$value){         $hashProperties[$value] = $key;      }      $toUpdate = array ();      foreach ($informations as $name=>$value){         if (isset ($hashProperties[$name])){            $toUpdate[$hashProperties[$name]] = $ct->quote ($value);         }      }      if (count ($toUpdate)){         $dbw = CopixDBFactory::getDbWidget ();         return $dbw->doUpdate ($this->userTable, $toUpdate, $condition);      }      return false;   }
   /**    * Check if the login and password match    * @param string $login the login    * @param string $password the password (clear)
    * @return boolean    */   function checkPassword ($login, $password) {      $ct = CopixDBFactory::getConnection ();      $dbw = CopixDbFactory::getDbWidget  ();      $query = 'SELECT '.$this->passwordfield.' FROM '.$this->userTable.' WHERE '.$this->loginField.'='.$ct->quote ($login);      if ($r = $dbw->fetchFirst ($request)){         return $r->{$this->passwordField} == $this->cryptPassword ($password);      }      return false;   }
   /**    * Gets the user properties    * @return array of CopixUserField    */   function getProperties (){      $toReturn = parent::getProperties ();      $toReturn['login']    = & new CopixUserField ('login', 'copix:auth.userField.login', 'copix:auth.userFieldDescription.login', 'string',                                    array (CopixUserField::forList()=>1,                                           CopixUserField::forAdmin()=>0,                                          CopixUserField::forUserUpdate()=>0,                                          CopixUserField::forUser()=>1));      $toReturn['password'] = & new CopixUserField ('password', 'copix:auth.userField.password', 'copix:auth.userFieldDescription.password', 'string',                                   array (CopixUserField::forAdmin()=>0,                                         CopixUserField::forAdmin()=>1,                                          CopixUserField::forUserUpdate()=>1,                                          CopixUserField::forUser()=>1));      $toReturn['email'] = & new CopixUserField ('email', 'copix:auth.userField.email', 'copix:auth.userFieldDescription.email', 'string',                                   array (CopixUserField::forList()=>1,                                          CopixUserField::forAdmin()=>1,                                          CopixUserField::forUserUpdate()=>1,                                          CopixUserField::forUser()=>1));      return $toReturn;   }}?>