<?php
/**
* @package   copix
* @subpackage SmartyPlugins
* @version   $Id: function.contenttype.php,v 1.7 2005/02/09 08:21:44 gcroes Exp $
* @author   Jouanneau Laurent
*           see copix.aston.fr for other contributors.
* @copyright 2001-2005 CopixTeam
* @link      http://copix.aston.fr
* @link      http://copix.org
* @licence  http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public Licence, see LICENCE file
*/

/**
 * Plugin smarty type fonction
 * Purpose:  set the content-type header to send
 *
 * Input:    mimetype = (optionnal) : the mime-type to send
 *           type    = (optionnal) an alias of mime-type, for easy use
 *             values:
 *                html  text/html
 *                xhtml application/xhtml+xml
 *                rdf   text/xml
 *                xbl   text/xml
 *                xml   text/xml
 *                rtf   text/rtf
 *                css   text/css
 *                txt   text/plain
 *                xul   application/vnd.mozilla.xul+xml
 *                rss   text/rss
 *                smil  application/smil
 *                svg   image/svg+xml
 *
 * If no parameters, content-type will not generate, and the default
 * content-type will be generated by web server
 * It verify that user agent support the content-type.
 * Examples:
 *   {contenttype mimetype=application/xhtml+xml}
 *   {contenttype type=xhtml}
 *
 */
function smarty_function_contenttype($params, &$smarty){
   if(isset($params['alias'])) $params['type']=$params['alias']; // hack for backward compatibility

   $mimetype = '';
   if(isset($params['mimetype'])){
      $mimetype = $params['mimetype'];
   }elseif(isset($params['type'])){
      $tabalias=array(
         'html'=>'text/html',
         'xhtml'=>'application/xhtml+xml',
         'rdf'=>'text/xml',
         'xbl'=>'text/xml',
         'xml'=>'text/xml',
         'rtf'=>'text/rtf',
         'css'=>'text/css',
         'txt'=>'text/plain',
         'xul'=>'application/vnd.mozilla.xul+xml',
         'rss'=>'text/rss',
         'smil'=>'application/smil',
         'svg'=>'image/svg+xml'
         );
      if(isset($tabalias[$params['type']])){
            $mimetype=$tabalias[$params['type']];
      }else
         $smarty->trigger_error('contenttype function : Unknow Alias type');
   }

   if($mimetype == 'application/xhtml+xml' && false === strstr($_SERVER['HTTP_ACCEPT'],$mimetype)) // hack for ie
      $mimetype='';
      
   if ( $mimetype !=''){ // non
      header('Content-type: '.$mimetype);
   }else
         $smarty->trigger_error('contenttype function : cant set content-type');

}
?>